"""
Telegram Bot for Pre-Open Scanner
Sends alerts every 10 seconds + Excel file at 9:08 AM

Run this alongside your backend server during market hours.
"""

import os
import time
import asyncio
from datetime import datetime, time as dt_time
from dotenv import load_dotenv
import requests

load_dotenv()

# Your bot token from BotFather
TELEGRAM_BOT_TOKEN = "8449739735:AAHe4sFKkQ81nDyvImu9WMMTlMr5DwjUYfo"

# Your Telegram user ID (or chat ID)
# To get your ID: Message @userinfobot on Telegram
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "YOUR_CHAT_ID_HERE")

# Backend API
BACKEND_URL = "http://localhost:8000"

# Alert thresholds
BREAKOUT_THRESHOLD = 2.0  # % change for breakout alert
VOLUME_THRESHOLD = 1.5  # 1.5x average volume

# Excel file path (generated by excel_exporter.py)
EXCEL_FILE_PATH = "preopen_data.xlsx"


def send_telegram_message(message: str):
    """Send a message via Telegram bot."""
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    data = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": message,
        "parse_mode": "HTML"
    }
    try:
        response = requests.post(url, data=data, timeout=10)
        return response.json()
    except Exception as e:
        print(f"Failed to send message: {e}")
        return None


def send_telegram_file(file_path: str, caption: str = ""):
    """Send a file via Telegram bot."""
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendDocument"
    try:
        with open(file_path, 'rb') as f:
            files = {'document': f}
            data = {'chat_id': TELEGRAM_CHAT_ID, 'caption': caption}
            response = requests.post(url, files=files, data=data, timeout=30)
            return response.json()
    except Exception as e:
        print(f"Failed to send file: {e}")
        return None


def get_top_movers():
    """Get top 5 gainers and losers from backend."""
    try:
        response = requests.get(
            f"{BACKEND_URL}/api/stocks",
            params={"sort_by": "change_pct", "order": "desc", "limit": 500},
            timeout=5
        )
        if response.status_code == 200:
            data = response.json()
            stocks = data.get("stocks", [])
            
            # Top 5 gainers
            gainers = [s for s in stocks if s.get("change_pct", 0) > 0][:5]
            
            # Top 5 losers
            losers = sorted(
                [s for s in stocks if s.get("change_pct", 0) < 0],
                key=lambda x: x.get("change_pct", 0)
            )[:5]
            
            return gainers, losers
        return [], []
    except Exception as e:
        print(f"Error fetching data: {e}")
        return [], []


def format_alert_message(gainers, losers):
    """Format Telegram message with top movers."""
    message = "🔔 <b>NSE Pre-Open Update</b>\n\n"
    
    message += "📈 <b>TOP GAINERS:</b>\n"
    for stock in gainers:
        symbol = stock.get("symbol", "").replace("NSE:", "").replace("-EQ", "")
        ltp = stock.get("ltp", 0)
        change_pct = stock.get("change_pct", 0)
        volume = stock.get("volume", 0)
        message += f"• <b>{symbol}</b>: ₹{ltp:.2f} ({change_pct:+.2f}%) | Vol: {volume:,}\n"
    
    message += "\n📉 <b>TOP LOSERS:</b>\n"
    for stock in losers:
        symbol = stock.get("symbol", "").replace("NSE:", "").replace("-EQ", "")
        ltp = stock.get("ltp", 0)
        change_pct = stock.get("change_pct", 0)
        volume = stock.get("volume", 0)
        message += f"• <b>{symbol}</b>: ₹{ltp:.2f} ({change_pct:+.2f}%) | Vol: {volume:,}\n"
    
    message += f"\n⏰ <i>Updated: {datetime.now().strftime('%H:%M:%S IST')}</i>"
    
    return message


def main():
    """Main loop - send alerts every 10 seconds during 9:00-9:07 AM."""
    print("="*60)
    print("TELEGRAM BOT - PRE-OPEN ALERTS")
    print("Window: 9:00 AM - 9:07 AM")
    print(f"Bot Token: {TELEGRAM_BOT_TOKEN[:20]}...")
    print(f"Chat ID: {TELEGRAM_CHAT_ID}")
    print("="*60)
    
    # Send startup message
    send_telegram_message("🤖 <b>Pre-Open Scanner Bot Started!</b>\n\nMonitoring stocks 9:00-9:07 AM IST")
    
    excel_sent = False
    
    while True:
        now = datetime.now()
        current_time = now.time()
        
        # Market hours: 9:00 AM - 9:07 AM
        start_time = dt_time(9, 0)
        end_time = dt_time(9, 7)
        excel_time = dt_time(9, 8)
        
        # During market hours: send alerts every 10 seconds
        if start_time <= current_time < end_time:
            print(f"\n[{now.strftime('%H:%M:%S')}] Fetching data...")
            
            gainers, losers = get_top_movers()
            
            if gainers or losers:
                message = format_alert_message(gainers, losers)
                result = send_telegram_message(message)
                if result:
                    print("✅ Alert sent!")
                else:
                    print("❌ Alert failed!")
            
            time.sleep(10)  # Wait 10 seconds
        
        # At 9:08 AM: send Excel file
        elif current_time >= excel_time and not excel_sent:
            print(f"\n[{now.strftime('%H:%M:%S')}] Sending Excel file...")
            
            if os.path.exists(EXCEL_FILE_PATH):
                caption = "📊 Pre-Open Data (9:00-9:07 AM)\n7 sheets, 1 per minute"
                result = send_telegram_file(EXCEL_FILE_PATH, caption)
                if result:
                    print("✅ Excel sent!")
                    excel_sent = True
                else:
                    print("❌ Excel send failed!")
            else:
                print(f"⚠️ Excel file not found: {EXCEL_FILE_PATH}")
                excel_sent = True  # Don't keep trying
            
            # Send final summary
            send_telegram_message("✅ <b>Pre-Open Session Complete!</b>\n\nMarket opens at 9:15 AM.")
            
            time.sleep(60)  # Wait 1 minute
        
        # Outside market hours: sleep longer
        else:
            if current_time < start_time:
                wait_seconds = (datetime.combine(now.date(), start_time) - now).total_seconds()
                print(f"\n⏳ Waiting until 9:00 AM ({wait_seconds:.0f} seconds)...")
            else:
                print(f"\n💤 Market hours ended. Exiting...")
                send_telegram_message("🛑 <b>Bot Stopped</b>\n\nPre-open session complete.")
                break
            
            time.sleep(30)  # Check every 30 seconds


if __name__ == "__main__":
    # Check if chat ID is set
    if TELEGRAM_CHAT_ID == "YOUR_CHAT_ID_HERE":
        print("\n⚠️ IMPORTANT: Set your TELEGRAM_CHAT_ID!")
        print("\n1. Message @userinfobot on Telegram")
        print("2. Copy your user ID")
        print("3. Add to .env: TELEGRAM_CHAT_ID=your_id")
        print("\nOr edit this file and replace YOUR_CHAT_ID_HERE")
        exit(1)
    
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n🛑 Bot stopped by user")
        send_telegram_message("🛑 <b>Bot Manually Stopped</b>")
